# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: ci

on:
#   push:
#     branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        deno: [1.x]

    steps:
    - uses: actions/checkout@v2
#     - name: Setup node.js
#       uses: actions/setup-node@v1
#       with:
#         node-version: 12.x
    - name: Setup Deno
      uses: denolib/setup-deno@v1.3.0
      with:
        deno-version: ${{ matrix.deno }}
    - name: Check code format
      run: deno fmt
    - name: Test
      run: deno test
